services:
  - type: web
    name: habitus-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
      - key: DB_URL
        value: jdbc:mysql://hopper.proxy.rlwy.net:28010/railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: quDpDypKJsnlgXrItkBeDSiwKAmkxQAN
